version: "3.9"

services: 
  server:
    build: .
    ports: 
      - '3030:3030'
  db:
    image: 'postgres'
    restart: always
    ports:
      - '4321:5432'
    environment:
      POSTGRES_USER: 'full_stack_user'
      POSTGRES_PASSWORD: '123456'
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports: 
        - '16543:80'
    depends_on: 
        - db  
