version: "3.9"

services: 
  server:
    build: .
    ports: 
      - '3030:3030'
    environment:
      ENV: prod
  db:
    image: 'postgres'
    restart: always
    ports:
      - '4321:5432'
    environment:
      POSTGRES_USER: 'full_stack_user'
      POSTGRES_PASSWORD: '123456'
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgres-data:/var/lib/postgresql/data